### ISSUE TITLE
Instead of Addresses we should show iovnames/starnames/blockchain addresses

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#1057]
Part of #1081.

Right now, in the menu, we have "Addresses".

Under this, we have 2 submenus:  "Your iovnames" and "Your blockchain addresses". Later on, we will have "Your starnames" as well.

Instead of putting these in the submenu, we should put them in the menu.  
"Your blockchain addresses" should be renamed to "Addresses"

**Comment by abefernan** [comment]
Since the current plan involves extracting "Your iovnames" & "Your starnames" functionality to a separate application in a separate repo, the only remaining subtab of the "Addresses" tab would be "Your blockchain addresses".

Since it won't make sense to have a tab with a single subtab, it should be removed, and I personally believe the name "Addresses" is better than "Your blockchain addresses", because they won't be confused with iovnames or starnames.

**Comment by annatorok** [comment]
@abefernan agreed, Addresses makes more sense.

**Comment by albertandrejev** [comment]
So, should this issue to be implemented? @annatorok

**Comment by abefernan** [comment]
@albertandrejev @annatorok I would not implement this until the extraction of names functionality to another repo is completely finished

**Comment by abefernan** [comment]
> Since the current plan involves extracting "Your iovnames" & "Your starnames" functionality to a separate application in a separate repo, the only remaining subtab of the "Addresses" tab would be "Your blockchain addresses".
> 
> Since it won't make sense to have a tab with a single subtab, it should be removed, and I personally believe the name "Addresses" is better than "Your blockchain addresses", because they won't be confused with iovnames or starnames.

@albertandrejev @annatorok and we should implement the changes in this comment, not the ones in the description of the ticket.

**Comment by davepuchyr** [comment]
This ticket is decoupled from https://github.com/iov-one/ponferrada/issues/1081 and will be closed via https://github.com/iov-one/ponferrada/issues/1113.
