### ISSUE TITLE
Account Status view : display human readable address

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#106]
The middle section of the Account Status view has an account selection box. On the same row, right justified show the human readable address associated with the account, if the user has created one (for example in the wallet application).

**Note**
-  if the user switches accounts the human readable account would change.
- See ticket comments
- This is the place where we should query for the human readable address: https://github.com/iov-one/ponferrada/blob/master/packages/sanes-chrome-extension/src/logic/persona/persona.ts#L154

**Aditional comments**
- Since an account has multiple addresses, only do one query per account (e.g. find the BNS address and query the name for the BNS address)
- Just assume the first chain of `this.signer` is the BNS chain (which we configure that way) and cast it to BnsConnection

**Comment by kmw101** [comment]
The position is shown in : https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/338674173

**Comment by webmaster128** [comment]
The logic screen suggests that a single human readable address is used for multiple accounts. However, this cannot work since one account means one chain-X address and multiple accounts mean multiple chain-X adddresses. This means the human readable address cannot be resolved to a single chain-X address anymore.

Instead, the human readable address should be an optional property of the account. So I suggest something like

<img width="381" alt="Bildschirmfoto 2019-05-14 um 12 13 22" src="https://user-images.githubusercontent.com/2603011/57690349-c6b1be80-7641-11e9-8278-02683d4afe90.png">

**Comment by kmw101** [comment]
I like that, it retains an overview and is clear which account is which.
