### ISSUE TITLE
Restore Account Part I

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#21]
This section has been replaced by the requirements below
-------------------------------------------------------------------
As a user I want to restore my account:

I am asked to enter my 12 recovery words. The label is "Restore your account with your recovery words" - the help text "Enter your recovery words here". 

There is a continue button which remains inactive until the recovery words have been entered (not there are 12 words expected).

If I click continue and I have entered the wrong recovery words I am shown an error toaster with the message "The words you entered are not correct".

If I have correctly entered the words I am shown the second part of the Restore Account workflow. https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/341373580

UX guide: https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/341373581

**Comment by albertandrejev** [comment]
I think second step should not go to https://github.com/iov-one/ponferrada/issues/22 . After you successfully enters 12 recovery words then you can choose new password. If you will click on "Continue" https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/341373580 you will be redirected to change password key and this is right. Also I think you should not go to this page after clicking on "Restore account" on the Login view (https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/349827786). You should be redirected to https://github.com/iov-one/ponferrada/issues/22 instead of recovering password by mnemonics. And then from this page (https://github.com/iov-one/ponferrada/issues/22) you can chose how to recover, using password hint or using recovery words.

**Comment by albertandrejev** [comment]
As far as I understand this system should be multiuser, so we need to provide user name on this page too.

**Comment by kmw101** [comment]
The original intent was that the system had an account and the ability to create sub accounts. It would seem that it has been built as a multi user system. As it has been implemented as a multi-user system then I will need to redesign the flows.

**Comment by kmw101** [comment]
The new story to reflect the multi-account logic
===============================

As a user I want to restore my **one** of my accounts:

I am asked to enter the unique identifier of the account I want to restore:

I am asked to enter my 12 recovery words associated with the unique identifier. The label is "Restore your account with your recovery words" - the help text "Enter your recovery words here".

There is a continue button which remains inactive until both the unique identifier and the recovery words have been entered (note there are 12 words expected).

If I click continue and I have entered the wrong recovery words that are associated with the unique identifier I am shown an error toaster with the message "The words you entered are not correct".

If I have correctly entered the words  associated with the unique identifier I am shown the second part of the Restore Account workflow. 
https://projects.invisionapp.com/share/PRPRZCQ9MHY#/screens/341373579

**Comment by kmw101** [comment]
This issue will be broken down into a discrete set of issues.
