### ISSUE TITLE
Create proposals on blockchain via governor instance

### ISSUE THREAD

**Issue by abefernan** [iov-one/ponferrada#509]
Make use of `governor.buildCreateProposalTx` to create a proposal and then sign it with `signAndPost()`.

Part of #400

- [ ] AddCommitteeMember
- [ ] RemoveCommitteeMember
- [ ] AmendElectionRuleThreshold
- [ ] AmendElectionRuleQuorum
- [ ] AddValidator
- [ ] RemoveValidator
- [ ] ReleaseGuaranteeFunds
- [ ] DistributeFunds
- [x] AmendProtocol

**Comment by webmaster128** [comment]
What is missing here? I see create proposal functionality (AmendProtocol) in code and will wrote it is working. Can you close or update the ticket, @abefernan?

**Comment by abefernan** [comment]
> 
> 
> What is missing here? I see create proposal functionality (AmendProtocol) in code and will wrote it is working. Can you close or update the ticket, @abefernan?

Because I thought maybe this should include support for the rest of the proposal types.

**Comment by webmaster128** [comment]
@abefernan okay, I created a checklist for visibility of that. Can you please keep it up to date? Thanks!

**Comment by webmaster128** [comment]
Let's break this down into smaller tickets, since not all proposal types are required for inital user testing.

1. AddCommitteeMember/RemoveCommitteeMember: https://github.com/iov-one/ponferrada/issues/614
2. AmendElectionRuleThreshold/AmendElectionRuleQuorum: https://github.com/iov-one/ponferrada/issues/615
3. AddValidator/RemoveValidator:  https://github.com/iov-one/ponferrada/issues/616
4. ReleaseGuaranteeFunds: https://github.com/iov-one/ponferrada/issues/617
5. DistributeFunds: https://github.com/iov-one/ponferrada/issues/618
