### ISSUE TITLE
Deploy the extension to Chrome Web Store 🚀⚒

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#55]
As a developer I want to deploy the chrome extension:

https://dev.to/gokatz/automate-your-chrome-extension-deployment-in-minutes-48gb

I need to link this to CI to automate the process.

**Comment by albertandrejev** [comment]
@kmw101 who can create Google Chrome Web Store API keys and provide them to me like it was described at https://dev.to/gokatz/automate-your-chrome-extension-deployment-in-minutes-48gb and https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md? In order to deploy extension to the WebStore I need this information.
