### ISSUE TITLE
Error in proposal title

### ISSUE THREAD

**Issue by kmw101** [iov-one/ponferrada#668]
Created a New Proposal : Clicked Submit and accept in the extension - nothing happened.

![image](https://user-images.githubusercontent.com/30301533/64356078-2b7e9380-cffa-11e9-8cb2-f29edb5adfbf.png)

Error message in Console

`Uncaught (in promise) Error: {
  "data": {},
  "log": "cannot check tx: migration: schema migration: validation: field \"Title\": invalid input",
  "code": 1000,
  "hash": {
    "0": 41,
    "1": 90,
    "2": 51,
    "3": 88,
    "4": 98,
    "5": 171,
    "6": 61,
    "7": 248,
    "8": 168,
    "9": 106,
    "10": 79,
    "11": 154,
    "12": 108,
    "13": 132,
    "14": 219,
    "15": 193,
    "16": 134,
    "17": 217,
    "18": 131,
    "19": 97,
    "20": 111,
    "21": 185,
    "22": 38,
    "23": 123,
    "24": 135,
    "25": 52,
    "26": 232,
    "27": 106,
    "28": 227,
    "29": 106,
    "30": 105,
    "31": 206
  }
}`

**Comment by webmaster128** [comment]
Okay, the pattern from weave is correct: `^[a-zA-Z0-9 _.-]{4,128}$`. Note that in the character class the `.` is the dot only, not _any character_.

I successfully submitted this title: `_-.0123456789 abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789 abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUV`. Martin probably used a `?` as part of his test title.

@abefernan can you pick up this ticket?

We need

- Longer valit title (maybe 50 instead of 30)
- Min length validation
- Validate character set
