### ISSUE TITLE
Check if we can open the Neuma extension automatically

### ISSUE THREAD

**Issue by annatorok** [iov-one/ponferrada#768]
**Goal:**
Wallet users will need to have the Neuma chrome extension installed on their computers in order to use the wallet. Right now, if the user clicks on the Continue button, it seems that nothing is happening, but on the extension, a notification ("1") will appear - the user can easily miss that he needs to do something.

**Question:**
Can we automatically open the extension window if there is something in the extension that needs to be approved? Not only at the signing it, but any time the user needs to take action there.

**Scope:**
To confirm if this is possible or not.

CC: @webmaster128

**Comment by albertandrejev** [comment]
This is not possible.
https://stackoverflow.com/questions/10479679/how-can-i-open-my-extensions-pop-up-with-javascript
> The philosophy for browser and page action popups is that they must be triggered by user action. Our suggestion is to use the new html notifications feature... (c) Chromium dev team.

In order to tell to user to open extension we have `Billboard` component. It shows full screen message  that user should interact with the extensions in order to continue. User can not interact with wallet until he/she will confirm request on the extension.

**Comment by webmaster128** [comment]
I had a second look into the APIs and documentation. I did not find anything that suggests this is possible.

If this is important, we should find out if MetaMask has this feature and how exactly they implement it.

**Comment by albertandrejev** [comment]
@annatorok sent me video how this was implemented in MetaMask. Very elegant. They are opening new browser window with content of the extension (as you know this is possible to access extension by internal URL).
https://internetofvalues.slack.com/files/UNANRTLBW/FNRV7E692/popup.mov

**Comment by albertandrejev** [comment]
We can investigate this and try to use. I don't think this is hard. But of course there is some limitation, like opened window focus etc.

**Comment by albertandrejev** [comment]
@webmaster128

**Comment by webmaster128** [comment]
@albertandrejev can you upload the video to Google drive? For some strange reason I cannot access the slack link.

In any case, this approach adds additional complexity to the product, since it creates cases where multiple UIs can be open at the same time and access the background script. This can create all kinds of funny data inconsistencies since the product was never designed for that. I'd be very careful adding this complexity if not strictly needed.

What about improving the Billboard design such that we have a visual pointer (some kind of arrow) that points the user to the icon in order to continue?

**Comment by annatorok** [comment]
@webmaster128 We are prepared to improve the design only and already have that ready. This ticket is just about checking if opening a popup is possible or not and probably in the first iteration, we won't go with this (until everything is thought out regarding the popup and how it would change the behaviour).

**Comment by albertandrejev** [comment]
> @albertandrejev can you upload the video to Google drive? For some strange reason I cannot access the slack link.

Link has been updated https://drive.google.com/open?id=1veeSnDX1aaVyvhGFmAg76lSwLKi3iQIo

**Comment by webmaster128** [comment]
Closing since this is "Done". @annatorok can you please close tickets instead of moving them? Closed tickets are moved to Done automatically.
