### ISSUE TITLE
Fix login billboard message in case if absent extensions

### ISSUE THREAD

**Issue by albertandrejev** [iov-one/ponferrada#872]
Right now billboard message appears and disappears very quickly (blink) in case if extension is not reachable.

**Comment by webmaster128** [comment]
I think there is nothing to fix. If the webapp cannot connect to the extension, `extensionRpcEndpoint.sendGetIdentitiesRequest` returns `undefined`, meaning "the endpoint was not available". This is what happens when you try to connect from a domain that is not whitelisted in the extension. In `getExtensionStatus()`, this `undefined` is then interpreted as `installed: false`.

Right now, the web application cannot differentiate if the extension is installed and not reachable or the extension is not installed. So not reachable is interpreted as not installed, which is the right interpretation if the wallet is deployed correctly.

**Comment by albertandrejev** [comment]
Yes, but this blinking looks ugly, that's the problem.

**Comment by webmaster128** [comment]
Oh, yeah, true. Thanks for improving the description.
